server.port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost/db
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.initialization-fail-timeout: 60000
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

spring.kafka:
  consumer:
    bootstrap-servers: localhost:9092
    group-id: io.realworld
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO
    io.realworld: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: "*"

---
spring.config.activate.on-profile: docker

spring.datasource.url: jdbc:mysql://mysql/db

spring.kafka:
  consumer.bootstrap-servers: kafka:9092
  producer.bootstrap-servers: kafka:9092